version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: forecast
      MYSQL_USER: forecast
      MYSQL_PASSWORD: password

  app:
    build: .
    depends_on:
    - mysql
    volumes:
    - .:/forecast
    ports:
    - "3000:3000"
    restart: always
    links:
    - "mysql"

volumes:
    db_data:
